import ExecutiveTemplate from "@/components/templates/ExecutiveTemplate";
import ClassicTemplate from "@/components/templates/ClassicTemplate";
import ModernTemplate from "@/components/templates/ModernTemplate";
import MinimalTemplate from "@/components/templates/MinimalTemplate";
import ProfessionalTemplate from "@/components/templates/ProfessionalTemplate";
import ProfessionalV2Template from "@/components/templates/ProfessionalV2Template";
import Professional2Template from "@/components/templates/Professional2Template";
import TechTemplate from "@/components/templates/TechTemplate";
import Creative2Template from "@/components/templates/Creative2Template";
import StrategicLeadershipTemplate from "@/components/templates/StrategicLeadershipTemplate";
import ImpactProTemplate from "@/components/templates/ImpactProTemplate";
import GitHubStyleTemplate from "@/components/templates/GitHubStyleTemplate";
import StructuredPhotoTemplate from "@/components/templates/StructuredPhotoTemplate";
import SiliconValleyTemplate from "@/components/templates/SiliconValleyTemplate";
import LatexAcademicTemplate from "@/components/templates/LatexAcademicTemplate";
import NordicSplitTemplate from "@/components/templates/NordicSplitTemplate";

export const TEMPLATES = [
  {
    id: "silicon-valley",
    name: "Silicon Valley Tech Lead",
    component: SiliconValleyTemplate,
    category: "Tech",
    emoji: "⚡",
    atsScore: 99,
  },
  {
    id: "latex-academic",
    name: "Stanford / LaTeX Academic Pro",
    component: LatexAcademicTemplate,
    category: "Academic",
    emoji: "🎓",
    atsScore: 100,
  },
  {
    id: "nordic-split",
    name: "Nordic Two-Column Architect",
    component: NordicSplitTemplate,
    category: "Executive",
    emoji: "📐",
    atsScore: 99,
  },
  {
    id: "executive",
    name: "The Wall Street / Ivy League",
    component: ExecutiveTemplate,
    category: "Executive",
    emoji: "🏛️",
    atsScore: 99,
  },
  {
    id: "classic",
    name: "The Open-Source Architect",
    component: ClassicTemplate,
    category: "Tech",
    emoji: "🛠️",
    atsScore: 99,
  },
  {
    id: "modern",
    name: "Linear / Vercel Minimalist",
    component: ModernTemplate,
    category: "Tech",
    emoji: "⚡",
    atsScore: 98,
  },
  {
    id: "minimal",
    name: "The Swiss Minimalist",
    component: MinimalTemplate,
    category: "Professional",
    emoji: "✨",
    atsScore: 99,
  },
  {
    id: "professional",
    name: "Professional",
    component: ProfessionalTemplate,
    category: "Professional",
    emoji: "💼",
    atsScore: 94,
  },
  {
    id: "professional-v2",
    name: "Professional V2",
    component: ProfessionalV2Template,
    category: "Professional",
    emoji: "📄",
    atsScore: 96,
  },
  {
    id: "professional2",
    name: "Professional Elite",
    component: Professional2Template,
    category: "Professional",
    emoji: "🏆",
    atsScore: 98,
  },
  {
    id: "tech",
    name: "Tech Developer",
    component: TechTemplate,
    category: "Tech",
    emoji: "💻",
    atsScore: 93,
  },
  {
    id: "GitHubStyle",
    name: "Metro Grid Narrative",
    component: GitHubStyleTemplate,
    category: "Professional",
    emoji: "🏙️",
    atsScore: 96,
  },
  {
    id: "creative2",
    name: "Studio & Editorial Portfolio",
    component: Creative2Template,
    category: "Creative",
    emoji: "🎨",
    atsScore: 98,
  },
  {
    id: "strategic-leader",
    name: "Strategic Leadership",
    component: StrategicLeadershipTemplate,
    category: "Leadership",
    emoji: "🎯",
    atsScore: 97,
  },
  {
    id: "impact-pro",
    name: "Impact Pro",
    component: ImpactProTemplate,
    category: "Professional",
    emoji: "⚡",
    atsScore: 98,
  },
  {
    id: "structured-photo",
    name: "Structured Photo Pro",
    component: StructuredPhotoTemplate,
    category: "Creative",
    emoji: "📸",
    atsScore: 95,
  },
];

export const TEMPLATE_COLOR_THEMES = {
  "latex-academic": [
    { id: "oxfordNavy", name: "Oxford Navy", primary: "#002147", emoji: "🎓" },
    { id: "stanfordCardinal", name: "Stanford Cardinal", primary: "#8c1515", emoji: "🌲" },
    { id: "cambridgeBlue", name: "Cambridge Blue", primary: "#005a9c", emoji: "🏛️" },
    { id: "ivyForest", name: "Ivy Forest", primary: "#065f46", emoji: "🌿" },
    { id: "mitBurgundy", name: "MIT Burgundy", primary: "#750014", emoji: "🔬" },
    { id: "princetonAmber", name: "Princeton Amber", primary: "#c2410c", emoji: "🐅" },
    { id: "slateMonochrome", name: "Slate Monochrome", primary: "#111827", emoji: "⚫" },
  ],
  "nordic-split": [
    { id: "osloCobalt", name: "Oslo Cobalt", primary: "#1d4ed8", emoji: "💙" },
    { id: "copenhagenEmerald", name: "Copenhagen Emerald", primary: "#047857", emoji: "🌲" },
    { id: "stockholmSlate", name: "Stockholm Slate", primary: "#1e293b", emoji: "📐" },
    { id: "bergenTeal", name: "Bergen Teal", primary: "#0f766e", emoji: "🌊" },
    { id: "arcticCyan", name: "Arctic Cyan", primary: "#0284c7", emoji: "💎" },
    { id: "gothenburgCopper", name: "Gothenburg Copper", primary: "#c2410c", emoji: "🧡" },
    { id: "charcoalOnyx", name: "Charcoal Onyx", primary: "#18181b", emoji: "⚫" },
  ],
  classic: [
    { id: "githubBlue", name: "GitHub Blue", primary: "#0969da", emoji: "🐙" },
    { id: "terminalGreen", name: "Terminal Green", primary: "#16a34a", emoji: "🌲" },
    { id: "monokaiPurple", name: "Monokai Violet", primary: "#7c3aed", emoji: "🔮" },
    { id: "cobaltTech", name: "Cobalt Tech", primary: "#1d4ed8", emoji: "🔷" },
    { id: "rubyRed", name: "Ruby Red", primary: "#b91c1c", emoji: "💎" },
    { id: "obsidianDark", name: "Obsidian Dark", primary: "#24292f", emoji: "⚫" },
  ],
  modern: [
    { id: "linearIndigo", name: "Linear Indigo", primary: "#5e6ad2", emoji: "🟣" },
    { id: "raycastEmerald", name: "Raycast Emerald", primary: "#10b981", emoji: "🟢" },
    { id: "arcElectric", name: "Arc Electric Blue", primary: "#2563eb", emoji: "⚡" },
    { id: "neonMagenta", name: "Neon Magenta", primary: "#c026d3", emoji: "🌸" },
    { id: "cyberAmber", name: "Cyber Amber", primary: "#d97706", emoji: "🟠" },
    { id: "vercelSlate", name: "Vercel Slate", primary: "#09090b", emoji: "⚫" },
  ],
  minimal: [
    { id: "charcoal", name: "Swiss Charcoal", primary: "#2d3748", emoji: "⚫" },
    { id: "navy", name: "Alpine Navy", primary: "#1e40af", emoji: "💼" },
    { id: "genevaSage", name: "Geneva Sage", primary: "#047857", emoji: "🌿" },
    { id: "baselOchre", name: "Basel Ochre", primary: "#b45309", emoji: "🏛️" },
    { id: "slate", name: "Zurich Slate", primary: "#475569", emoji: "🌑" },
    { id: "graphite", name: "Graphite Onyx", primary: "#18181b", emoji: "⬛" },
  ],
  professional: [
    { id: "royalSapphire", name: "Royal Sapphire", primary: "#1d4ed8", emoji: "💙" },
    { id: "emeraldPrestige", name: "Emerald Prestige", primary: "#047857", emoji: "🌲" },
    { id: "cabernetBurgundy", name: "Cabernet Wine", primary: "#831843", emoji: "🍷" },
    { id: "nordicTeal", name: "Nordic Teal", primary: "#0f766e", emoji: "🌊" },
    { id: "imperialPlum", name: "Imperial Plum", primary: "#6b21a8", emoji: "🔮" },
    { id: "warmTerracotta", name: "Warm Amber", primary: "#c2410c", emoji: "🧡" },
    { id: "deepOcean", name: "Deep Ocean", primary: "#0369a1", emoji: "⚓" },
    { id: "titaniumSlate", name: "Titanium Slate", primary: "#1e293b", emoji: "⚫" },
  ],
  "professional-v2": [
    { id: "royalSapphire", name: "Royal Sapphire", primary: "#1d4ed8", emoji: "💙" },
    { id: "emeraldPrestige", name: "Emerald Prestige", primary: "#047857", emoji: "🌲" },
    { id: "cabernetBurgundy", name: "Cabernet Wine", primary: "#831843", emoji: "🍷" },
    { id: "nordicTeal", name: "Nordic Teal", primary: "#0f766e", emoji: "🌊" },
    { id: "imperialPlum", name: "Imperial Plum", primary: "#6b21a8", emoji: "🔮" },
    { id: "warmTerracotta", name: "Warm Amber", primary: "#c2410c", emoji: "🧡" },
    { id: "deepOcean", name: "Deep Ocean", primary: "#0369a1", emoji: "⚓" },
    { id: "titaniumSlate", name: "Titanium Slate", primary: "#1e293b", emoji: "⚫" },
  ],
  professional2: [
    { id: "royalSapphire", name: "Royal Sapphire", primary: "#1d4ed8", emoji: "💙" },
    { id: "emeraldPrestige", name: "Emerald Prestige", primary: "#047857", emoji: "🌲" },
    { id: "cabernetBurgundy", name: "Cabernet Wine", primary: "#831843", emoji: "🍷" },
    { id: "nordicTeal", name: "Nordic Teal", primary: "#0f766e", emoji: "🌊" },
    { id: "titaniumSlate", name: "Titanium Slate", primary: "#1e293b", emoji: "⚫" },
    { id: "warmTerracotta", name: "Warm Amber", primary: "#c2410c", emoji: "🧡" },
  ],
  executive: [
    { id: "navy", name: "Wall Street Navy", primary: "#1e3a8a", emoji: "💼" },
    { id: "burgundy", name: "Oxford Crimson", primary: "#831843", emoji: "🍷" },
    { id: "forest", name: "Ivy Forest", primary: "#065f46", emoji: "🌲" },
    { id: "royalSapphire", name: "Swiss Banking Blue", primary: "#1d4ed8", emoji: "🏦" },
    { id: "warmBronze", name: "Executive Bronze", primary: "#9a3412", emoji: "🪙" },
    { id: "slate", name: "Manhattan Slate", primary: "#1e293b", emoji: "🏛️" },
    { id: "charcoal", name: "Big Law Charcoal", primary: "#1f2937", emoji: "⚫" },
  ],
  tech: [
    { id: "githubBlue", name: "GitHub Blue", primary: "#0969da", emoji: "🐙" },
    { id: "supabaseEmerald", name: "Supabase Green", primary: "#059669", emoji: "⚡" },
    { id: "raycastIndigo", name: "Raycast Indigo", primary: "#4f46e5", emoji: "🟣" },
    { id: "cyberCyan", name: "Docker Cyan", primary: "#0891b2", emoji: "🐳" },
    { id: "rustAmber", name: "Rust Amber", primary: "#d97706", emoji: "🦀" },
    { id: "pythonGold", name: "Python Gold", primary: "#ca8a04", emoji: "🐍" },
    { id: "vercelStealth", name: "Vercel Stealth", primary: "#18181b", emoji: "⚫" },
  ],
  GitHubStyle: [
    { id: "metroNavy", name: "Metro Navy", primary: "#13315c", emoji: "🏙️" },
    { id: "metroTeal", name: "Metro Teal", primary: "#0f4c5c", emoji: "🌆" },
    { id: "metroBurgundy", name: "Metro Burgundy", primary: "#5e2129", emoji: "🏢" },
    { id: "cyberIndigo", name: "Cyber Indigo", primary: "#3730a3", emoji: "🟣" },
    { id: "terminalGreen", name: "Terminal Green", primary: "#14532d", emoji: "🌲" },
    { id: "electricCobalt", name: "Electric Cobalt", primary: "#1e40af", emoji: "⚡" },
    { id: "amberOchre", name: "Amber Ochre", primary: "#9a3412", emoji: "🪵" },
    { id: "obsidianSlate", name: "Obsidian Slate", primary: "#18181b", emoji: "⚫" },
  ],
  creative2: [
    { id: "teakWood", name: "Honey Teak & Oak", primary: "#9a3412", emoji: "🪵" },
    { id: "smokedWalnut", name: "Smoked Walnut", primary: "#d97706", emoji: "🪵" },
    { id: "nordicBirch", name: "Nordic Birch & Pine", primary: "#2d6a4f", emoji: "🌲" },
    { id: "rosewoodMahogany", name: "Mahogany & Rosewood", primary: "#881337", emoji: "🪵" },
    { id: "charredEbony", name: "Charred Ebony", primary: "#262626", emoji: "🪵" },
  ],
  "strategic-leader": [
    { id: "teal", name: "Strategic Teal", primary: "#0d7377", emoji: "🌊" },
    { id: "purple", name: "Executive Purple", primary: "#6b46c1", emoji: "🔮" },
    { id: "burgundy", name: "Leadership Crimson", primary: "#9b2c2c", emoji: "🍷" },
    { id: "navy", name: "Corporate Navy", primary: "#1e3a8a", emoji: "💼" },
    { id: "emerald", name: "Emerald Growth", primary: "#047857", emoji: "🌲" },
  ],
  "impact-pro": [
    { id: "emerald", name: "Emerald Growth", primary: "#047857", emoji: "💚" },
    { id: "blue", name: "Impact Blue", primary: "#1e40af", emoji: "💙" },
    { id: "purple", name: "Venture Purple", primary: "#7e22ce", emoji: "💜" },
    { id: "orange", name: "Velocity Orange", primary: "#c2410c", emoji: "🧡" },
    { id: "cyan", name: "Cyan Impact", primary: "#0284c7", emoji: "💎" },
  ],
  "structured-photo": [
    { id: "coral", name: "Coral", primary: "#e05c5c", emoji: "🟥" },
    { id: "terracotta", name: "Terracotta", primary: "#d9694f", emoji: "🟧" },
    { id: "rose", name: "Rose", primary: "#db5d74", emoji: "🌹" },
  ],
  "silicon-valley": [
    { id: "stripeIndigo", name: "Stripe Indigo", primary: "#4f46e5", emoji: "🟣" },
    { id: "cyberEmerald", name: "Cyber Emerald", primary: "#059669", emoji: "🟢" },
    { id: "electricCobalt", name: "Electric Cobalt", primary: "#2563eb", emoji: "⚡" },
    { id: "crimsonEdge", name: "Crimson Edge", primary: "#be123c", emoji: "🌹" },
    { id: "nordicTeal", name: "Nordic Teal", primary: "#0f766e", emoji: "🌊" },
    { id: "midnightSlate", name: "Midnight Slate", primary: "#1e293b", emoji: "🔵" },
    { id: "monochromePro", name: "Monochrome Pro", primary: "#18181b", emoji: "⚫" },
  ],
};
